// import { GetCouponDataRes } from "../../services";

// export const couponData_3: GetCouponDataRes[] = [
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
// ];
// export const couponData_4: GetCouponDataRes[] = [
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
//   {
//     couponId: 1,
//     couponCode: "URL링크에서발급",
//     couponUrl: "/img/brand/starbucks.svg",
//     description: "자바칩 프라푸치노",
//     popularity: 50,
//     likeCount: 30,
//     dislikeCount: 12,
//     brandName: "스타벅스",
//     couponName: "자바칩 프라푸치노",
//     startDate: "2023.08.02",
//     endDate: "2023.09.02",
//     brandImgUrl: "",
//     email: "",
//   },
// ];
